import Head from 'next/head'
import ThemeBtn from './components/ThemeBtn'
import { useTheme } from 'next-themes';


export default function Home() {
  const { theme } = useTheme();

  console.log(theme)

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className={`w-full h-[100vh] bg-cover p-5 ${theme === 'light' ? 'bg-[url("../assets/light-theme.jpg")]' : 'bg-[url("../assets/dark-theme.jpg")]'}`}>
          <ThemeBtn />
        </div>
      </main>
    </>
  )
}